// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_zikirData from "./routes/api/zikirData.ts";
import * as $counter_id_ from "./routes/counter/[id].tsx";
import * as $index from "./routes/index.tsx";
import * as $list from "./routes/list.tsx";
import * as $CounterTasbeeh from "./islands/CounterTasbeeh.tsx";
import * as $TasbeehList from "./islands/TasbeehList.tsx";
import * as $Translate from "./islands/Translate.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/zikirData.ts": $api_zikirData,
    "./routes/counter/[id].tsx": $counter_id_,
    "./routes/index.tsx": $index,
    "./routes/list.tsx": $list,
  },
  islands: {
    "./islands/CounterTasbeeh.tsx": $CounterTasbeeh,
    "./islands/TasbeehList.tsx": $TasbeehList,
    "./islands/Translate.tsx": $Translate,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
